# Generated by Django 5.0.7 on 2024-08-07 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_network_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ['name'], 'verbose_name': 'Сеть', 'verbose_name_plural': 'Сети'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
