# Generated by Django 5.0.7 on 2024-08-07 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_network_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name': 'Сеть', 'verbose_name_plural': 'Сети'},
        ),
        migrations.AlterField(
            model_name='product',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='network.network', verbose_name='Сеть'),
        ),
    ]
