# Generated by Django 5.0.7 on 2024-08-09 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_remove_networknode_supplier_networknode_suppliers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='suppliers',
        ),
        migrations.RemoveField(
            model_name='product',
            name='network_node',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.CreateModel(
            name='ElectronicsNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('products', models.JSONField()),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.IntegerField(choices=[(0, 'Factory'), (1, 'Retail Chain'), (2, 'Individual Entrepreneur')])),
                ('contacts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='network.supplier')),
                ('suppliers', models.ManyToManyField(blank=True, related_name='networks', to='network.supplier')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='NetworkNode',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
