# Generated by Django 5.0.7 on 2024-08-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_contactinfo_remove_networknode_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networknode',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='networknode',
            name='contact_info',
            field=models.ManyToManyField(blank=True, related_name='network_nodes', to='network.contactinfo'),
        ),
    ]
