# Generated by Django 5.0.7 on 2024-08-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0017_remove_networknode_contact_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networknode",
            name="level",
            field=models.IntegerField(
                choices=[
                    (0, "Завод"),
                    (1, "Розничная сеть"),
                    (2, "Индивидуальный предприниматель"),
                ],
                default=0,
            ),
        ),
    ]
